version: "3"

services:
  builder:
    build:
      context: builder
    image: eosio/builder

  nodeosd:
    build:
      context: .
    image: eosio/eos
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir

  tkeosd:
    image: eosio/eos
    command: /opt/eosio/bin/tkeosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8999
    hostname: tkeosd
    links:
      - nodeosd
    volumes:
      - tkeosd-data-volume:/opt/eosio/bin/data-dir

volumes:
  nodeos-data-volume:
    external: true
  tkeosd-data-volume:
    external: true
